import {parseTwConcertViewCalendar} from '../lib/twconcertview-discovery.js';
import {parseArtistsTwIcs,parseArtistsTwHtml} from '../lib/artists-tw-discovery.js';

const UA='Mozilla/5.0 (compatible; NEUL-Cloudflare/1.3; +concert-discovery)';
const SOURCE_DEFS=[
 {id:'tixcraft',label:'tixCraft 拓元',url:'https://tixcraft.com/activity',host:/^(?:www\.)?tixcraft\.com$|\.tixcraft\.com$/i},
 {id:'kktix',label:'KKTIX',url:'https://kktix.com/events',host:/^(?:www\.)?kktix\.com$|\.kktix\.cc$/i},
 {id:'ticketplus',label:'Ticket Plus 遠大售票',url:'https://ticketplus.com.tw/activity',host:/^(?:www\.)?ticketplus\.com\.tw$|\.ticketplus\.com\.tw$/i},
 {id:'kham',label:'寬宏售票 KHAM',url:'https://kham.com.tw/application/UTK01/UTK0101_06.aspx?CATEGORY=205&TYPE=1',host:/^(?:www\.)?kham\.com\.tw$|\.kham\.com\.tw$/i},
 {id:'famiticket',label:'全網購票網 FamiTicket',url:'https://www.famiticket.com.tw/',host:/^(?:www\.)?famiticket\.com\.tw$|\.famiticket\.com\.tw$/i},
 {id:'udn',label:'udn 售票網',url:'https://tickets.udnfunlife.com/application/UTK01/UTK0101_.aspx',host:/^(?:tickets\.)?udnfunlife\.com$|\.udnfunlife\.com$/i},
 {id:'ibon',label:'ibon 售票',url:'https://ticket.ibon.com.tw/',host:/^(?:ticket\.)?ibon\.com\.tw$|\.ibon\.com\.tw$/i},
 {id:'mna',label:'MNA 牛耳藝術',url:'https://ticket.mna.com.tw/',host:/^(?:ticket\.)?mna\.com\.tw$|\.mna\.com\.tw$/i},
 {id:'era',label:'年代售票',url:'https://ticket.com.tw/application/UTK01/UTK0101_.aspx',host:/^(?:www\.)?ticket\.com\.tw$|\.ticket\.com\.tw$/i},
 {id:'tixfun',label:'TixFun',url:'https://www.tixfun.com/',host:/^(?:www\.)?tixfun\.com$|\.tixfun\.com$/i},
 {id:'opentix',label:'OPENTIX',url:'https://www.opentix.life/events',host:/^(?:www\.)?opentix\.life$|\.opentix\.life$/i},
 {id:'fansigo',label:'FANSI GO',url:'https://go.fansi.me/',host:/^(?:www\.)?fansigo\.com$|\.fansigo\.com$|^go\.fansi\.me$/i},
 {id:'indievox',label:'iNDIEVOX',url:'https://www.indievox.com/activity/latest?type=table',host:/^(?:www\.)?indievox\.com$|\.indievox\.com$/i},
 {id:'books',label:'博客來售票',url:'https://tickets.books.com.tw/',host:/^(?:tickets\.)?books\.com\.tw$|\.books\.com\.tw$/i},
 {id:'livenation',label:'Live Nation Taiwan',url:'https://www.livenation.com.tw/event/allevents',host:/^(?:www\.)?livenation\.com\.tw$|\.livenation\.com\.tw$/i}
];
const VENUE_DEFS=[
 {id:'venue-taipei-arena',label:'臺北小巨蛋官方',url:'https://www.arena.taipei/',venue:'臺北小巨蛋 Taipei Arena'},
 {id:'venue-kaohsiung-arena',label:'高雄巨蛋官方',url:'https://www.kaoarena.com.tw/Home/CalendarList?Category=%E8%97%9D%E6%96%87%E8%A1%A8%E6%BC%94',venue:'高雄巨蛋 Kaohsiung Arena'},
 {id:'venue-tmc',label:'臺北流行音樂中心官方',url:'https://www.tmc.taipei/tw/blog/show',venue:'臺北流行音樂中心 Taipei Music Center'},
 {id:'venue-ticc',label:'TICC 官方活動行事曆',url:'https://www.ticc.com.tw/wSite/sp?BaseDSD=7&CtUnit=96&ctNode=318&mp=1&xdUrl=%2FwSite%2Fap%2Flp_Activity_3.jsp',venue:'臺北國際會議中心 TICC'},
 {id:'venue-zepp',label:'Zepp New Taipei 官方',url:'https://www.zepp.co.jp/hall/newtaipei/schedule/',venue:'Zepp New Taipei'},
 {id:'venue-kmc',label:'高雄流行音樂中心官方',url:'https://kpmc.com.tw/program/',venue:'高雄流行音樂中心 Kaohsiung Music Center'}
];
const KEYWORDS=/(concert|world\s*tour|asia\s*tour|\btour\b|fan\s?(?:meeting|con|concert)|\blive\b|festival|award|showcase|演唱會|巡迴|見面會|音樂會|專場|粉絲見面|音樂節|頒獎典禮|公演|演出)/i;
const WRAPPER=/(vip\s*upgrade|升級\s*vip|mastercard專區|返鄉專車|接駁|交通車|shuttle|merch|周邊|福利套票|套票專區|package\s*only)/i;
const NON_MUSIC=/(展覽|講座|工作坊|研討會|論壇|課程|市集|路跑|球賽|棒球|籃球|足球|電影|親子劇|音樂劇)/i;
const VENUES=['臺北大巨蛋','台北大巨蛋','Taipei Dome','臺北小巨蛋','台北小巨蛋','Taipei Arena','高雄巨蛋','Kaohsiung Arena','高雄國家體育場','世運主場館','國立體育大學綜合體育館','林口體育館','NTSU ARENA','台北國際會議中心','臺北國際會議中心','TICC','臺北流行音樂中心','台北流行音樂中心','Taipei Music Center','高雄流行音樂中心','LIVE WAREHOUSE','Zepp New Taipei','Legacy TERA','Legacy Taipei','Clapper Studio','WESTAR','The Wall','Billboard Live TAIPEI','臺大綜合體育館','台大綜合體育館','高雄展覽館','南港展覽館'];
const decode=s=>String(s||'').replace(/<!\[CDATA\[|\]\]>/g,'').replace(/&amp;/g,'&').replace(/&#39;|&apos;/g,"'").replace(/&quot;/g,'"').replace(/&nbsp;/g,' ').replace(/&#x2F;/g,'/').replace(/<br\s*\/?\s*>/gi,' ').replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim();
const abs=(u,b)=>{try{return new URL(u,b).toString()}catch{return''}};
const slug=s=>decode(s).toLowerCase().normalize('NFKD').replace(/[^a-z0-9\u4e00-\u9fff]+/g,'-').replace(/^-|-$/g,'').slice(0,86);
const twToday=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Taipei',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const isoDate=d=>`${d}T00:00:00+08:00`;
function parseDate(text){const s=decode(text);let m=s.match(/(20\d{2})\s*[\/\.\-年]\s*(\d{1,2})\s*[\/\.\-月]\s*(\d{1,2})/);if(m)return`${m[1]}-${String(m[2]).padStart(2,'0')}-${String(m[3]).padStart(2,'0')}`;m=s.match(/(20\d{2})(\d{2})(\d{2})/);if(m)return`${m[1]}-${m[2]}-${m[3]}`;return'';}
function findVenue(text,fallback=''){const s=decode(text);return VENUES.find(v=>s.toLowerCase().includes(v.toLowerCase()))||fallback||'';}
function cityFromVenue(v=''){const s=String(v);if(/高雄|Kaohsiung/i.test(s))return'Kaohsiung';if(/台中|臺中|Taichung/i.test(s))return'Taichung';if(/桃園|林口|國立體育大學|NTSU|Taoyuan/i.test(s))return'Taoyuan';if(/新北|Zepp|New Taipei/i.test(s))return'New Taipei';if(/台北|臺北|Taipei|TICC|Legacy|Clapper|WESTAR|The Wall|Billboard/i.test(s))return'Taipei';return'';}
function venueModelFor(v=''){const rules=[[/臺?北大巨蛋|Taipei Dome/i,'taipei-dome'],[/臺?北小巨蛋|Taipei Arena/i,'taipei-arena'],[/林口體育館|國立體育大學|NTSU/i,'ntsu-arena'],[/高雄巨蛋|Kaohsiung Arena/i,'kaohsiung-arena'],[/高雄國家體育場|世運主場館|National Stadium/i,'kaohsiung-stadium'],[/臺?北流行音樂中心|Taipei Music Center/i,'taipei-music-center'],[/TICC|臺?北國際會議中心/i,'ticc'],[/高雄流行音樂中心|海音館|Kaohsiung Music Center/i,'kaohsiung-music-center'],[/臺?大綜合體育館|NTU Sports/i,'ntu-sports-center'],[/Zepp New Taipei/i,'zepp-new-taipei'],[/Legacy TERA/i,'legacy-tera']];return rules.find(([r])=>r.test(v))?.[1]||null;}
function inferType(t=''){return/festival|音樂節|祭/i.test(t)?'FESTIVAL':/fan\s*(?:meeting|con)|見面會/i.test(t)?'FAN MEETING':'CONCERT';}
function inferMarket(t=''){if(/[ぁ-んァ-ヶ]/u.test(t)||/Japan|J-?POP/i.test(t))return'JP';if(/K-?POP|Korea|韓國|BTS|IVE|aespa|TREASURE|NCT|PLAVE|LE SSERAFIM/i.test(t))return'KR';if(/[A-Za-z]/.test(t))return'INTL';return'TW';}
function isPerformance(title,context=''){const t=decode(title),c=decode(context);if(!t||t.length<2||WRAPPER.test(t))return false;if(NON_MUSIC.test(t)&&!KEYWORDS.test(t))return false;return KEYWORDS.test(t)||KEYWORDS.test(c)||/[A-Za-z0-9\u4e00-\u9fff]{2,}\s+(?:IN|in)\s+(?:TAIPEI|KAOHSIUNG)/.test(t);}
function eventFrom({source,title,date,venue,url}){if(!date||!title)return null;const venueOnly=source.id.startsWith('venue-'),market=inferMarket(title),model=venueModelFor(venue),id=`auto-${source.id}-${slug(`${date}-${title}-${venue}`)}`;return{id,artist:title.split(/[|｜–—]/)[0].trim().slice(0,100),shortArtist:title.replace(/[^A-Za-z0-9]/g,'').slice(0,5).toUpperCase()||'LIVE',title,type:inferType(title),region:'TW',market,start:isoDate(date),end:null,timeConfirmed:false,venue,city:cityFromVenue(venue),statusLabel:venueOnly?'場館官方已公開':'自動發現',ticketStatus:'CHECK OFFICIAL',generalSale:null,ticketing:venueOnly?'依主辦／官方售票平台公告':source.label,price:'依官方售票頁公告',sourceName:source.label,sourceUrl:url||source.url,sharedSourceUrl:venueOnly,verified:true,autoUpdated:true,checkedAt:new Date().toISOString(),tags:[market,venueOnly?'VENUE OFFICIAL':'TICKET SOURCE','AUTO'],venueModelId:model,summary:venueOnly?'由場館官方行事曆交叉發現；售票、舞台與入場資訊請回官方頁核對。':'由官方售票／主辦來源自動發現；NEUL 會持續回補票價、座位圖與活動專屬 3D。',notes:[venueOnly?'場館行事曆用於 coverage gap 偵測。':'票價與座位配置仍以官方最新公告為準。'],sourceRefs:[{name:source.label,url:url||source.url}]};}
function parseGeneric(html,base,source){const out=[];let m;const re=/<a\b[^>]*href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi;while((m=re.exec(html))&&out.length<260){const href=abs(m[1],base),title=decode(m[2]);if(!href||!title)continue;const context=decode(html.slice(Math.max(0,m.index-700),Math.min(html.length,re.lastIndex+900)));if(!isPerformance(title,context))continue;const date=parseDate(context)||parseDate(title);if(!date||date<twToday().slice(0,4)+'-01-01')continue;const venue=findVenue(context,source.venue||'待官方資料回補');const e=eventFrom({source,title,date,venue,url:href});if(e)out.push(e);}const by=new Map();for(const e of out){const k=`${e.start.slice(0,10)}|${e.title.toLowerCase()}|${e.venue.toLowerCase()}`;if(!by.has(k))by.set(k,e);}return[...by.values()].slice(0,80);}
async function fetchText(url,timeoutMs=6000,accept='text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',maxChars=500000){const ac=new AbortController(),timer=setTimeout(()=>ac.abort(),timeoutMs),started=Date.now();try{const res=await fetch(url,{signal:ac.signal,redirect:'follow',headers:{'user-agent':UA,'accept-language':'zh-TW,zh;q=0.9,en;q=0.7',accept}});if(!res.ok)throw new Error(`HTTP ${res.status}`);return{ok:true,status:res.status,url:res.url||url,text:(await res.text()).slice(0,maxChars),ms:Date.now()-started};}catch(e){return{ok:false,error:String(e?.message||e),url,ms:Date.now()-started,text:''};}finally{clearTimeout(timer)}}
export async function fetchSource(source,{timeoutMs=6000}={}){const r=await fetchText(source.url,timeoutMs);const checkedAt=new Date().toISOString();if(!r.ok)return{id:source.id,label:source.label,ok:false,error:r.error,count:0,events:[],checkedAt,ms:r.ms};const events=parseGeneric(r.text,r.url,source);return{id:source.id,label:source.label,ok:true,status:r.status,count:events.length,events,checkedAt,ms:r.ms,zeroResultWarning:events.length===0};}
export async function fetchSourceGroup(ids,{timeoutMs=6000}={}){const defs=[...SOURCE_DEFS,...VENUE_DEFS].filter(x=>ids.includes(x.id)),out=[];for(let i=0;i<defs.length;i+=6){const batch=defs.slice(i,i+6),rs=await Promise.allSettled(batch.map(x=>fetchSource(x,{timeoutMs})));rs.forEach((r,j)=>out.push(r.status==='fulfilled'?r.value:{id:batch[j].id,label:batch[j].label,ok:false,error:String(r.reason),events:[],count:0,checkedAt:new Date().toISOString()}));}return out;}
export async function fetchAllSources(opts={}){return fetchSourceGroup([...SOURCE_DEFS,...VENUE_DEFS].map(x=>x.id),opts)}
function monthUrls(cursor=0,count=4){const d=new Date(),year=Number(new Intl.DateTimeFormat('en',{timeZone:'Asia/Taipei',year:'numeric'}).format(d)),month=Number(new Intl.DateTimeFormat('en',{timeZone:'Asia/Taipei',month:'numeric'}).format(d));const urls=['https://twconcertview.com/calendar'];for(let i=0;i<count;i++){const n=month-1+Number(cursor)+i,y=year+Math.floor(n/12),m=n%12+1;urls.push(`https://twconcertview.com/calendar?year=${y}&month=${String(m).padStart(2,'0')}`);}return urls;}
export async function fetchTwcvReference({timeoutMs=6000,cursor=0,monthsPerCycle=4}={}){const urls=monthUrls(cursor,Math.max(1,Math.min(4,monthsPerCycle))),pages=[],errors=[];for(const url of urls){const r=await fetchText(url,timeoutMs,undefined,1200000);if(!r.ok){errors.push(r.error);continue;}pages.push(parseTwConcertViewCalendar(r.text,{sourceUrl:r.url}));}const map=new Map();let referenceCount=0,raw=0;for(const p of pages){referenceCount=Math.max(referenceCount,Number(p.referenceCount||0));raw+=Number(p.rawOccurrenceCount||0);for(const e of p.events||[]){if(String(e.start||'').slice(0,10)<twToday())continue;const k=`${String(e.start).slice(0,10)}|${e.title.toLowerCase()}|${e.venue.toLowerCase()}`;if(!map.has(k))map.set(k,e);}}const events=[...map.values()].sort((a,b)=>new Date(a.start)-new Date(b.start));return{id:'twcv',label:'twconcertview 行事曆（補漏參考）',ok:pages.length>0,count:events.length,referenceCount,parsedCount:events.length,showingParsedCount:raw||events.length,events,checkedAt:new Date().toISOString(),successfulPages:pages.length,monthsScanned:Math.max(0,urls.length-1),nextCursor:(Number(cursor)+Math.max(1,monthsPerCycle))%18,errors};}
export async function fetchArtistsReference({timeoutMs=6000}={}){const errors=[],map=new Map(),add=xs=>{for(const e of xs||[]){if(String(e.start||'').slice(0,10)<twToday())continue;const k=`${String(e.start).slice(0,10)}|${String(e.title).toLowerCase()}|${String(e.venue).toLowerCase()}`;if(!map.has(k))map.set(k,e)}};let referenceCount=0,checked=0;const feed=await fetchText('https://tw-gigs.orbis-f60.workers.dev/feeds/all.ics',timeoutMs,'text/calendar,text/plain;q=0.9,*/*;q=0.5',1200000);if(feed.ok){add(parseArtistsTwIcs(feed.text));checked++;}else errors.push(feed.error);const root=await fetchText('https://www.artists.tw/gigs/',timeoutMs,undefined,1200000);if(root.ok){const p=parseArtistsTwHtml(root.text,root.url);referenceCount=p.referenceCount||0;add(p.events);checked++;}else errors.push(root.error);const events=[...map.values()].sort((a,b)=>new Date(a.start)-new Date(b.start));return{id:'artists-tw',label:'Artists.tw 現場音樂索引（補漏參考）',ok:checked>0,count:events.length,referenceCount,parsedCount:events.length,events,checkedAt:new Date().toISOString(),checkedUrls:checked,errors};}
function xmlVal(block,tag){const m=block.match(new RegExp(`<${tag}[^>]*>([\\s\\S]*?)<\\/${tag}>`,'i'));return decode(m?.[1]||'')}
export async function fetchNewsCategory(category='kr',{timeoutMs=6000,q=''}={}){const queries={kr:'韓星 KPOP 台灣 演唱會 when:7d',jp:'日本 歌手 台灣 演唱會 when:7d',tw:'台灣 歌手 演唱會 when:7d',west:'歐美 歌手 台灣 演唱會 when:7d',other:'台灣 演唱會 音樂活動 when:7d'};const query=`${queries[category]||queries.kr}${q?` ${q}`:''}`.trim(),url='https://news.google.com/rss/search?q='+encodeURIComponent(query)+'&hl=zh-TW&gl=TW&ceid=TW:zh-Hant',r=await fetchText(url,timeoutMs,'application/rss+xml,application/xml,text/xml;q=0.9,*/*;q=0.5',700000),cutoff=Date.now()-7*864e5,results=[];if(r.ok){let m,re=/<item>([\s\S]*?)<\/item>/gi;while((m=re.exec(r.text))&&results.length<48){const b=m[1],title=xmlVal(b,'title'),link=xmlVal(b,'link'),publishedAtRaw=xmlVal(b,'pubDate'),source=xmlVal(b,'source'),ts=Date.parse(publishedAtRaw)||0;if(title&&link&&ts>=cutoff)results.push({title,url:link,publishedAt:new Date(ts).toISOString(),source:source||'Google News'});}}return{category,ok:r.ok,results:results.sort((a,b)=>Date.parse(b.publishedAt)-Date.parse(a.publishedAt)).slice(0,36),checkedAt:new Date().toISOString(),error:r.ok?'':r.error};}
const EXTRA_HOSTS=['assets.kktix.io','static.tixcraft.com','networksites.livenationinternational.com','livenationinternational.com','livenation.com.tw','weverse.io','ygfamily.com','arena.taipei','tmc.taipei','kaoarena.com.tw','kpmc.com.tw','farglorydome.com.tw','news-images.tvbs.com.tw','ntsu.edu.tw','phk.ntsu.edu.tw','dst.tycg.gov.tw','tycg.gov.tw','rent.pe.ntu.edu.tw','pe.ntu.edu.tw','ntu.edu.tw','ticc.com.tw','tainex.com.tw','zepp.co.jp','kcg.gov.tw','kph.tw'];
export function trustedHost(host=''){const h=host.toLowerCase();return SOURCE_DEFS.some(x=>x.host.test(h))||EXTRA_HOSTS.some(x=>h===x||h.endsWith('.'+x));}
export function isTrustedUrl(raw){try{const u=new URL(raw);return u.protocol==='https:'&&trustedHost(u.hostname)}catch{return false}}
export {SOURCE_DEFS,VENUE_DEFS};
