import fs from 'node:fs';
import handler from '../api/entertainment-news.js';

let ok=true; const fail=(m,x='')=>{console.error('FAIL',m,x);ok=false;};
const html=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8');
const css=fs.readFileSync(new URL('../styles.css',import.meta.url),'utf8');
const news=fs.readFileSync(new URL('../news.js',import.meta.url),'utf8');
const sw=fs.readFileSync(new URL('../sw.js',import.meta.url),'utf8');
const api=fs.readFileSync(new URL('../api/entertainment-news.js',import.meta.url),'utf8');
const i18n=fs.readFileSync(new URL('../i18n.js',import.meta.url),'utf8');
for(const id of ['entertainmentNews','newsGrid','newsStatus','newsSearchForm','newsSearchInput','newsRefreshBtn','newsCategorySelect']) if(!html.includes(`id="${id}"`)) fail(`missing news UI: ${id}`);
for(const c of ['kr','jp','tw','west','other']) if(!html.includes(`<option value="${c}">`)) fail(`missing news category option: ${c}`);
if(!/const state = \{ category: "kr"/.test(news)) fail('Korean news is not default');
if(!/href="#entertainmentNews"[^>]*><span>[^<]+<\/span>新聞<\/a>/.test(html)) fail('mobile News navigation item missing');
if(/class="mobile-bottom"[\s\S]{0,800}href="#planner"/.test(html)) fail('mobile planner nav should be replaced by News');
if(!/grid-template-columns:repeat\(5,minmax\(0,1fr\)\)/.test(css)) fail('mobile bottom nav not five columns');
if(!/@media\(max-width:720px\)[\s\S]*?\.events-modal-close\{position:fixed;top:calc\(env\(safe-area-inset-top\) \+ 10px\)/.test(css)) fail('mobile event modal close not safe-area fixed');
if(!/\.events-modal-card\{box-sizing:border-box;width:100%!important;max-width:100%!important;height:100dvh/.test(css)) fail('mobile event modal full-width containment missing');
if(!/\.events-calendar-grid\{grid-template-columns:repeat\(7,minmax\(0,1fr\)\)/.test(css)) fail('mobile calendar seven-column containment missing');
const newsPos=html.indexOf('id="entertainmentNews"'), footerPos=html.indexOf('<footer');
if(newsPos<0 || footerPos<0 || newsPos>footerPos) fail('news section is not at the bottom before footer');
if(!/jp:\s*\{[\s\S]*?label:\s*"日本"/.test(api)) fail('Japan news API category missing');
if(!/other:\s*\{[\s\S]*?-JPOP[\s\S]*?-日本藝人/.test(api)) fail('Other news category does not exclude Japan terms');
if(!i18n.includes("'日本':'Japan'") || !i18n.includes("'新聞':'News'")) fail('new news labels missing English i18n');
if(!/news\.google\.com\/rss\/search/.test(api)) fail('free public news feed missing');
if(!sw.includes('"/news.js"')) fail('news.js not cached by PWA');

const fixture=`<?xml version="1.0"?><rss><channel><item><title><![CDATA[IVE 回歸新消息 - Test Media]]></title><link>https://example.com/a</link><pubDate>Sun, 20 Sep 2026 10:00:00 GMT</pubDate><description><![CDATA[<p>summary</p>]]></description><source url="https://example.com">Test Media</source></item><item><title>第二則 - Media B</title><link>https://example.com/b</link><pubDate>Sun, 20 Sep 2026 09:00:00 GMT</pubDate><source url="https://example.com">Media B</source></item></channel></rss>`;
const realFetch=global.fetch;
global.fetch=async ()=>({ok:true,status:200,text:async()=>fixture});
let status=0, body=null, headers={};
const req={method:'GET',query:{category:'jp',q:'藤川千愛'}};
const res={setHeader:(k,v)=>headers[k]=v,status(n){status=n;return this;},json(v){body=v;return this;}};
await handler(req,res);
global.fetch=realFetch;
if(status!==200) fail('news API mock status',status);
if(body?.category!=='jp'||body?.results?.length!==2) fail('Japan news API parse',body);
if(body?.results?.[0]?.title!=='IVE 回歸新消息'||body?.results?.[0]?.source!=='Test Media') fail('news API title/source normalization',body?.results?.[0]);
if(!headers['Cache-Control']?.includes('s-maxage=900')) fail('news API cache header missing',headers);

if(!ok) process.exit(1);
console.log('NEUL news/mobile checks passed · News replaces Plan · 5 categories incl. Japan · bottom news · safe mobile list/calendar · RSS parser/cache');
