import fs from 'node:fs';
import { seedEvents } from '../data/events.js';
import { parseArtistsTwIcs, parseArtistsTwHtml } from '../lib/artists-tw-discovery.js';
import { parseTwConcertViewCalendar } from '../lib/twconcertview-discovery.js';
let ok=true;const fail=(m,x='')=>{console.error('FAIL',m,x);ok=false;};
const pkg=JSON.parse(fs.readFileSync(new URL('../package.json',import.meta.url),'utf8'));
const app=fs.readFileSync(new URL('../app.js',import.meta.url),'utf8');
const api=fs.readFileSync(new URL('../api/events.js',import.meta.url),'utf8');
const sw=fs.readFileSync(new URL('../sw.js',import.meta.url),'utf8');
if(pkg.version!=='0.40.17')fail('package version',pkg.version);
const now=new Date('2026-09-24T00:00:00+08:00').getTime();
const upcoming=seedEvents.filter(e=>new Date(e.end||e.start||0).getTime()>=now-86400000);
if(upcoming.length<120)fail('offline upcoming fallback must no longer collapse to ~83',upcoming.length);
if(upcoming.filter(e=>e.referenceBootstrap).length<35)fail('reference bootstrap too small',upcoming.filter(e=>e.referenceBootstrap).length);
const ics=`BEGIN:VCALENDAR\nBEGIN:VEVENT\nDTSTART;TZID=Asia/Taipei:20261002T193000\nSUMMARY:PREP Live in Taipei\nLOCATION:Legacy Taipei\nURL:https://www.artists.tw/gigs/prep/\nEND:VEVENT\nBEGIN:VEVENT\nDTSTART;VALUE=DATE:20261031\nSUMMARY:WHIB\nLOCATION:Clapper Studio\nEND:VEVENT\nEND:VCALENDAR`;
const ie=parseArtistsTwIcs(ics);if(ie.length!==2||ie[0].start!=='2026-10-02T19:30:00+08:00'||!ie.every(e=>e.referenceOnly))fail('Artists.tw ICS parser',ie);
const html=`<div>目前收錄 427 場演出</div><article><h3>ZAZEN to VOOID</h3><div>Legacy Taipei · 台北市</div><time>2026年9月24日</time></article><article><h3>WHIB</h3><div>Clapper Studio · 台北市</div><time>2026年10月31日</time></article>`;
const he=parseArtistsTwHtml(html);if(he.referenceCount!==427||he.events.length!==2)fail('Artists.tw HTML parser',he);
const tw=parseTwConcertViewCalendar('近期 317 場演出\n2026-09-24｜ZAZEN BOYS & VOOID｜Legacy Taipei');if(tw.referenceCount!==317)fail('TWCV reference count',tw);
if(!/discoverArtistsTwGigs/.test(api)||!/supplementaryReferenceCount/.test(api))fail('Artists.tw API integration missing');
if(!/TWCV 場次參考/.test(app)||!/現場音樂索引/.test(app))fail('dual reference UI missing');
if(!/neul-v0\.40\.17/.test(sw)||!/data\/reference-bootstrap\.js/.test(sw))fail('service worker v0.40.17/reference bootstrap missing');
if(!ok)process.exit(1);
console.log(`NEUL v0.40.17 checks passed · offline upcoming ${upcoming.length} · Artists.tw ICS/HTML reference discovery · dual coverage telemetry`);
