import fs from 'node:fs';
import {retainRecentArchive} from '../api/events.js';
const app=fs.readFileSync('app.js','utf8');
const api=fs.readFileSync('api/events.js','utf8');
const enh=fs.readFileSync('enhancements.js','utf8');
let ok=true; const fail=(m,x)=>{console.error(m,x??'');ok=false;};
if(!/const ARCHIVE_LIMIT = 20/.test(app)) fail('client archive limit missing');
if(!/retainRecentArchive/.test(app)) fail('client archive compaction missing');
if(!/Archive · 20/.test(enh)) fail('archive UI limit label missing');
if(!/const ARCHIVE_LIMIT = 20/.test(api)) fail('server archive limit missing');
if(!/retainRecentArchive\(allEvents\)/.test(api)) fail('server response archive compaction missing');
if(!/archiveLimit: ARCHIVE_LIMIT/.test(api)||!/archiveCount/.test(api)) fail('archive metadata missing');
if(!/!eventLifecycle\(e,now\)\.ended/.test(app)) fail('ended events are not excluded from seat-map 3D hydration');
if(!/return !eventLifecycle\(event,now\)\.ended/.test(app)) fail('ended events are not excluded from 3D layout options');
if(/layout\.id===state\.layoutId\) return true/.test(app)) fail('selected ended layout bypass still present');
if(!/setInterval\(\(\)=>\{ if\(!document\.hidden\) loadEvents/.test(app)) fail('hourly auto update missing');
const now=Date.parse('2026-09-21T18:00:00+08:00');
const ended=Array.from({length:25},(_,i)=>({id:`past-${i+1}`,start:new Date(now-(i+1)*86400000).toISOString(),region:'TW'}));
const future=[{id:'future-a',start:new Date(now+86400000).toISOString(),region:'TW'},{id:'future-b',start:new Date(now+2*86400000).toISOString(),region:'TW'}];
const compact=retainRecentArchive([...ended,...future],now,20);
const keptPast=compact.filter(x=>x.id.startsWith('past-'));
if(compact.length!==22) fail('archive compaction total wrong',compact.length);
if(keptPast.length!==20) fail('archive cap not exactly 20',keptPast.length);
if(!keptPast.some(x=>x.id==='past-1')||keptPast.some(x=>x.id==='past-25')) fail('archive did not retain most recent 20');
if(!future.every(x=>compact.some(y=>y.id===x.id))) fail('upcoming event lost during archive compaction');
if(!ok) process.exit(1);
console.log('NEUL v0.40.9 Archive20 automation checks passed');
