export const seedEvents = [
  {id:'treasure-new-wav-2026',date:'2026-09-26',artist:'TREASURE',title:'TREASURE THE STAGE 2026 NEW WAV : LIVE IN KAOHSIUNG',venue:'高雄巨蛋 Kaohsiung Arena',city:'高雄',category:'韓國',source:'Weverse / 高雄巨蛋',sourceUrl:'https://weverse.io/treasure/notice/37253',ticketUrl:'',price:'依官方售票頁公告',mapUrl:'',layoutId:'auto-treasure-new-wav-kaohsiung-2026',stage:'end',featured:true,image:''},
  {id:'sj83z-1983-2026',date:'2026-10-03',artist:'SUPER JUNIOR-83z',title:'2026 SUPER JUNIOR-83z FANCON TOUR [1983] in KAOHSIUNG',venue:'高雄流行音樂中心 海音館',city:'高雄',category:'韓國',source:'KKTIX',sourceUrl:'https://chuanyeah.kktix.cc/events/080cefdf?locale=zh-TW',ticketUrl:'https://chuanyeah.kktix.cc/events/080cefdf?locale=zh-TW',price:'NT$6,480 / 6,080 / 5,680 / 4,680 / 3,680 / 2,340',mapUrl:'https://assets.kktix.io/organization_resource_files/59413/79383/SJ83z_%E5%BA%A7%E4%BD%8D%E5%9C%96%E8%A6%96%E7%B7%9A%E9%81%AE%E6%93%8B_0729_%E9%AB%98%E9%9B%84.jpg',layoutId:'sj83z-1983-kaohsiung-2026',stage:'end',featured:true,image:''},
  {id:'plave-keep-it-manic-2026',date:'2026-10-23',artist:'PLAVE',title:'World Tour [KEEP IT MANIC] in Taipei',venue:'NTSU ARENA (LINKOU ARENA)',city:'桃園',category:'韓國',source:'Weverse / tixCraft',sourceUrl:'https://weverse.io/plave/notice/38153',ticketUrl:'https://tixcraft.com/activity/detail/26_plavetp',price:'依官方售票頁公告',mapUrl:'https://tixcraft.com/activity/detail/26_plavetp',layoutId:'plave-keep-it-manic-2026',stage:'end',featured:true,image:''},
  {id:'kim-ji-won-wonderland-2026',date:'2026-11-08',artist:'KIM JI WON',title:'2026 KIM JI WON FANMEETING ＜WONEDERLAND＞ in TAIPEI',venue:'LEGACY TERA',city:'台北',category:'韓國',source:'tixCraft',sourceUrl:'https://tixcraft.com/activity/detail/26_kimjiwon',ticketUrl:'https://tixcraft.com/activity/detail/26_kimjiwon',price:'NT$5,800 / 4,980 / 身障席 2,490',mapUrl:'',layoutId:'auto-kim-ji-won-wonederland-taipei-2026',stage:'end',featured:false,image:''},
  {id:'lsf-pureflow-2026',date:'2026-11-14',artist:'LE SSERAFIM',title:'2026 LE SSERAFIM TOUR ‘PUREFLOW’ IN TAIPEI',venue:'國立體育大學綜合體育館 NTSU ARENA',city:'桃園',category:'韓國',source:'tixCraft',sourceUrl:'https://tixcraft.com/activity/detail/26_lsf',ticketUrl:'https://tixcraft.com/activity/detail/26_lsf',price:'VIP NT$6,980 / 6,380 / 5,880 / 4,680 / 3,680',mapUrl:'https://static.tixcraft.com/images/activity/field/26_lsf_2346a9e447c58490112b8fda1aacef0c.jpg',layoutId:'le-sserafim-pureflow-2026',stage:'end',featured:true,image:''},
  {id:'aaa-kaohsiung-2026',date:'2026-12-05',artist:'Asia Artist Awards',title:'2026 Asia Artist Awards in Kaohsiung',venue:'高雄國家體育場（世運主場館）',city:'高雄',category:'韓國',source:'tixCraft',sourceUrl:'https://tixcraft.com/activity/detail/26_aaa',ticketUrl:'https://tixcraft.com/activity/detail/26_aaa',price:'NT$6,980 / 5,980 / 4,980 / 3,980 / 2,980 / 1,980',mapUrl:'https://static.tixcraft.com/images/activity/field/26_aaa_ff695286699ccaa0c40a381cb828ceb9.jpg',layoutId:'auto-aaa-2026-kaohsiung',stage:'end',featured:true,image:''},
  {id:'skz-run-it-2026',date:'2026-12-12',artist:'Stray Kids',title:'World Tour <RUN IT TAIPEI>',venue:'臺北大巨蛋 Taipei Dome',city:'台北',category:'韓國',source:'Live Nation Taiwan',sourceUrl:'https://www.livenation.com.tw/en/event/stray-kids-world-tour-run-it-taipei--taipei-tickets-edp1695879',ticketUrl:'https://www.livenation.com.tw/en/event/stray-kids-world-tour-run-it-taipei--taipei-tickets-edp1695879',price:'VIP NT$7,880 / 6,880 / 5,880 / 4,880 / 3,880 / 2,880',mapUrl:'https://static.tixcraft.com/images/activity/field/26_straykids_94646da4bfc54de7f8ccfdd2f7ea570e.jpg',layoutId:'skz-run-it-2026',stage:'end',featured:true,image:''},
  {id:'yesung-ordinary-2026',date:'2026-12-26',artist:'YESUNG',title:'10TH ANNIVERSARY TOUR — ABOUT THE THINGS WE CALLED ORDINARY',venue:'NTSU ARENA',city:'桃園',category:'韓國',source:'Weverse',sourceUrl:'https://weverse.io/superjunior/notice/39022',ticketUrl:'',price:'依官方售票頁公告',mapUrl:'',layoutId:'auto-yesung-ordinary-taipei-2026',stage:'end',featured:false,image:''},
  {id:'nct127-redline-2027',date:'2027-01-02',artist:'NCT 127',title:"5TH TOUR 'NEO CITY : THE REDLINE'",venue:'臺北小巨蛋 Taipei Arena',city:'台北',category:'韓國',source:'Weverse',sourceUrl:'https://weverse.io/nct127/notice/37278',ticketUrl:'',price:'TBA',mapUrl:'',layoutId:'auto-nct127-redline-taipei-2027',stage:'end',featured:true,image:''}
];

export const venueCatalog = [
  {id:'taipei-dome',name:'臺北大巨蛋 Taipei Dome',city:'台北',kind:'dome',floors:4,capacity:'40,000+'},
  {id:'taipei-arena',name:'臺北小巨蛋 Taipei Arena',city:'台北',kind:'arena',floors:3,capacity:'11,000+'},
  {id:'kaohsiung-arena',name:'高雄巨蛋 Kaohsiung Arena',city:'高雄',kind:'arena',floors:3,capacity:'13,000+'},
  {id:'ntsu-arena',name:'國立體育大學綜合體育館 NTSU ARENA',city:'桃園',kind:'arena',floors:3,capacity:'15,000+'},
  {id:'tmc',name:'臺北流行音樂中心 Taipei Music Center',city:'台北',kind:'hall',floors:3,capacity:'5,000+'},
  {id:'ticc',name:'台北國際會議中心 TICC',city:'台北',kind:'theater',floors:3,capacity:'3,000+'},
  {id:'kpmc',name:'高雄流行音樂中心 海音館',city:'高雄',kind:'hall',floors:3,capacity:'5,000+'},
  {id:'zepp',name:'Zepp New Taipei',city:'新北',kind:'livehouse',floors:2,capacity:'2,000+'},
  {id:'legacy-tera',name:'LEGACY TERA',city:'台北',kind:'livehouse',floors:2,capacity:'3,000+'},
  {id:'world-games',name:'高雄國家體育場（世運主場館）',city:'高雄',kind:'stadium',floors:3,capacity:'40,000+'}
];
